# 若设置为true则会在控制台输出debug信息
debug: false

# 生成地形的最低高度, 1.17-应使用0, 1.18+的主世界类型使用-64
lowest: 0

# 生成地形的最高高度, 1.17-应使用255, 1.18+的主世界类型使用319
highest: 255

# 每个地图块的半径
radius: 64

# 用于游戏的世界名字, 若不存在则会自动生成
world: game