# 若设置为true则会在控制台输出debug信息
debug: false

# 生成地形的最低高度, 1.17-应使用0, 1.18+的主世界类型使用-64
lowest: 0

# 生成地形的最高高度, 1.17-应使用255, 1.18+的主世界类型使用319
highest: 255

# 每个地图块的半径
radius: 64

# 用于游戏的世界名字, 若不存在则会自动生成
world: game

# 指令黑名单
# 拥有权限节点 `edropper.bypass.command` 的玩家跳过此检测
prevent_command:
  # 设置为true则按阻止玩家使用匹配的指令, 反之则仅允许玩家使用列出的指令
  is_black: false
  # 正则列表
  regexes:
    - /tp\s+.*